apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-service-fastapi
  namespace: sample-service
spec:
  replicas: 1
  selector:
    matchLabels: { app: sample-service-fastapi }
  template:
    metadata:
      labels: { app: sample-service-fastapi }
    spec:
      containers:
        - name: app
          image: nginx:1.27
          ports: [{ containerPort: 80 }]
